version: '3.9'

services:
  worker-app-server:
    build:
      dockerfile: dev.Dockerfile
      context: .
    networks:
      - worker-app-network
    ports:
      - "8081:8081"
    expose:
      - "8081"
    volumes:
      - .:/app
    env_file:
      - .env

networks:
  worker-app-network:
    driver: bridge
